defaultEncoding = "msgpack"

[[mappings]]
# utilities/<type>/<direction>/<sensor>
topic = "utilities/+/+/+"
template = "{{index .topiclevels 1}}-{{index .topiclevels 3}},unit={{.unit}},direction={{index .topiclevels 2}} value={{.value}} {{.timestamp}}\n"
